# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "\
    ${LAYERDIR}/appends/packagegroup-core.bbappend \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
    "

# Optionally use an external app, if set to 1, include the bbappend for the app recipe
USE_EXTERNAL_APP ?= "0"
BBFILES += "\
    ${@ '${LAYERDIR}/appends/hello-app.bbappend' \
        if d.getVar('USE_EXTERNAL_APP') == '1' else ''} \
    ${@ '${LAYERDIR}/appends/use-hello-lib.bbappend' \
        if d.getVar('USE_EXTERNAL_APP') == '1' else ''} \
    "

BBFILE_COLLECTIONS += "meta-application"
BBFILE_PATTERN_meta-application = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-application = "6"

LAYERDEPENDS_meta-application = "core"
LAYERSERIES_COMPAT_meta-application = "scarthgap"
