# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

# Optionally use an external library, if set to 1, include the bbappend for the lib recipe
USE_EXTERNAL_LIB ?= "0"
BBFILES += "${@ '${LAYERDIR}/appends/hello-lib.bbappend' if d.getVar('USE_EXTERNAL_LIB') == '1' else '' }"

BBFILE_COLLECTIONS += "meta-library"
BBFILE_PATTERN_meta-library = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-library = "6"

LAYERDEPENDS_meta-library = "core"
LAYERSERIES_COMPAT_meta-library = "scarthgap"
